#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use App\Command\ConsumerCommand;
use App\Command\ProducerCommand;
use Symfony\Component\Console\Application;

$app = new Application();

$app->add(new ConsumerCommand());
$app->add(new ProducerCommand());

$app->run();
